#:kivy 1.11.1

<BarGraphL3Screen>:
    name: 'bar_graph_l3_screen'
    id: bar_graph_l3_screen

    GridLayout:
        # Window level 1
        cols:1
        spacing: 10

        GridLayout:
            cols: 1
            size_hint_y: 4.8
            spacing: 5

            GridLayout:
                rows: 1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.25
                    Rectangle:
                        pos: self.pos
                        size: self.size


            GridLayout:
                rows: 1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.25
                    Rectangle:
                        pos: self.pos
                        size: self.size

            GridLayout:
                rows: 1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.25
                    Rectangle:
                        pos: self.pos
                        size: self.size
            GridLayout:
                rows: 1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.25
                    Rectangle:
                        pos: self.pos
                        size: self.size

            GridLayout:
                rows: 1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.25
                    Rectangle:
                        pos: self.pos
                        size: self.size

        GridLayout:
            rows: 1

            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.25
                Rectangle:
                    pos: self.pos
                    size: self.size
